defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

name: ${hydra.job.name}
account: "gts-dxu345-rl2"
qos: "inferno"
timeout_min: 2880

cpus_per_task: 8
nodes: 1
tasks_per_node: 1
gres: "gpu:h200:1"

additional_parameters:
  constraint: "rhel9"
  requeue: true
