defaults:
  - submitit_slurm

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

name: ${hydra.job.name}
partition: "hoffman-lab"
account: "hoffman-lab"

cpus_per_task: 12

nodes: ${launch_params.nodes}                      
tasks_per_node: ${launch_params.gpus_per_node}    
gres: "gpu:l40s:${eval:'${launch_params.gpus_per_node} * ${launch_params.nodes}'}"

qos: "short"
timeout_min: 2880 # 80 hours

additional_parameters:
  requeue: true
  gpus-per-node: "a40:1"