# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: "${name}_${description}_${hydra:runtime.choices.data}_${hydra:runtime.choices.model}_${hydra:runtime.choices.trainer}_${now:%Y-%m-%d_%H-%M-%S}"
  save_dir: "${paths.output_dir}"
  offline: False
  id: "${name}_${description}_${hydra:runtime.choices.data}_${hydra:runtime.choices.model}_${hydra:runtime.choices.trainer}_${now:%Y-%m-%d_%H-%M-%S}" # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "viperx_egoverse"
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  entity: "sylvain-beuret-epfl" # set to name of your wandb team
  group: "${name}_${hydra:runtime.choices.data}"
  tags:
    - "${hydra:runtime.choices.data}"
    - "${hydra:runtime.choices.model}"
    - "${hydra:runtime.choices.trainer}"
  job_type: ""
