_target_: egomimic.pl_utils.pl_data_utils.MultiDataModuleWrapper
train_datasets:
  dataset1:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: rldb
    mode: train
    embodiment: eva_bimanual
    cache_root: "/coc/flash7/rpunamiya6/.cache"
    filters:
      task: fold clothes
    local_files_only: true

  dataset2:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: rldb
    mode: train
    embodiment: aria_bimanual
    cache_root: "/coc/flash7/rpunamiya6/.cache"
    filters:
      task: fold_clothes_indomain
    local_files_only: true


  dataset3:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: rldb
    mode: train
    valid_ratio: 0.5
    embodiment: mecka_bimanual
    cache_root: "/coc/flash7/rpunamiya6/.cache"
    filters:
      task: fold_clothes
    local_files_only: true

valid_datasets:
  dataset1:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: rldb
    mode: valid
    embodiment: eva_bimanual
    cache_root: "/coc/flash7/rpunamiya6/.cache"
    filters:
      task: fold clothes
    local_files_only: true

  dataset2:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: rldb
    mode: valid
    embodiment: aria_bimanual
    cache_root: "/coc/flash7/rpunamiya6/.cache"
    filters:
      task: fold_clothes_indomain
    local_files_only: true


  dataset3:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: rldb
    mode: valid
    percent: 0.5
    embodiment: mecka_bimanual
    cache_root: "/coc/flash7/rpunamiya6/.cache"
    filters:
      task: fold_clothes
    local_files_only: true
  
train_dataloader_params:
  dataset1:
    batch_size: 32
    num_workers: 10
  dataset2:
    batch_size: 32
    num_workers: 10
  dataset3:
    batch_size: 32
    num_workers: 10
valid_dataloader_params:
  dataset1:
    batch_size: 32
    num_workers: 10
  dataset2:
    batch_size: 32
    num_workers: 10
  dataset3:
    batch_size: 32
    num_workers: 10