_target_: egomimic.pl_utils.pl_data_utils.MultiDataModuleWrapper

train_datasets:
  dataset1:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: "rldb"
    mode: train
    embodiment: "eva_bimanual"
    cache_root: "/coc/flash7/scratch/.cache/"
    filters: 
      task: "fold clothes"
    local_files_only: True
    debug: False

valid_datasets:
  dataset1:
    _target_: egomimic.rldb.utils.S3RLDBDataset
    bucket_name: "rldb"
    mode: valid
    embodiment: "eva_bimanual"
    cache_root: "/coc/flash7/scratch/.cache/"
    filters: 
      task: "fold clothes"
    local_files_only: True
    debug: False

train_dataloader_params:
  dataset1:
    batch_size: 32
    num_workers: 10

valid_dataloader_params:
  dataset1:
    batch_size: 32
    num_workers: 10