_target_: egomimic.pl_utils.pl_data_utils.MultiDataModuleWrapper
train_datasets:
  dataset1:
    _target_: rldb.utils.MultiRLDBDataset
    datasets:
      rl2_lab:
        _target_: rldb.utils.FolderRLDBDataset
        folder_path: /coc/cedarp-dxu345-0/datasets/egoverse/put_cup_on_saucer_egoverse/put_cup_on_saucer_rl2
        embodiment: aria_bimanual
        mode: train
        local_files_only: true
    embodiment: aria_bimanual

valid_datasets:
  dataset1:
    _target_: rldb.utils.MultiRLDBDataset
    datasets:
      eth_lab:
        _target_: rldb.utils.FolderRLDBDataset
        folder_path: /coc/cedarp-dxu345-0/datasets/egoverse/put_cup_on_saucer_egoverse/put_cup_on_saucer_song
        embodiment: aria_bimanual
        mode: valid
        local_files_only: true
    embodiment: "aria_bimanual"

train_dataloader_params:
  dataset1:
    batch_size: 2
    num_workers: 10

valid_dataloader_params:
  dataset1:
    batch_size: 2
    num_workers: 10