_target_: egomimic.pl_utils.pl_data_utils.MultiDataModuleWrapper
train_datasets:
  dataset1:
    _target_: egomimic.rldb.utils.FolderRLDBDataset
    folder_path: /data/sybeuret/.local/huggingface/lerobot/lerobot/pick_sponge_egov
    embodiment: viperx_right_arm
    mode: train
    local_files_only: true

valid_datasets:
  dataset1:
    _target_: egomimic.rldb.utils.FolderRLDBDataset
    folder_path: /data/sybeuret/.local/huggingface/lerobot/lerobot/pick_sponge_egov
    embodiment: viperx_right_arm
    mode: valid
    local_files_only: true

train_dataloader_params:
  dataset1:
    batch_size: 8
    num_workers: 4

valid_dataloader_params:
  dataset1:
    batch_size: 8
    num_workers: 4